Vehicle Gyromats
TFlippy/kag_territorycontrol pull request #169
Opened 2021-05-26 21:50 UTC by Wunarg

The following vehicles now work with gyromats: (Square root of effect)
Bomber
ArmoredBomber
ArmoredCar
Car
Catapult
SteamTank
Ballista

This does allow the car and the armored car to sort of fly at 2 to 3 gyromats due to how base kag handles vehicles, but considering the difficulty of obtaining gyromat and the durability of cars this seems fine, additionally this flying is quite hard to use

2021-05-26 21:54 UTC, Wunarg commented
Additional Note: Only affects horizontal speed of ballons and ballons will drop them when you press the bomb release button similar to any item put into its inventory so its somewhat hard to use for bombing runs

2021-05-27 06:48 UTC, Wunarg commented
Note: Other vehicles firing speed is not affected this is just the catapult since it seems the most mechanical

2021-05-27 10:05 UTC, Vam-Jam requested changes

2021-05-27 10:05 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Core_Dev/Entities/Vehicles/BomberCommon.as
> +		if(this.exists("gyromat_acceleration"))
space between if (

2021-05-27 10:05 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Core_Dev/Entities/Vehicles/VehicleCommon.as
> +						if(this.exists("gyromat_acceleration"))
and here

2021-05-27 10:05 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Weapons_Dev/Entities/Vehicles/Catapult/Catapult.as
> +			if(this.exists("gyromat_acceleration"))
space

2021-05-27 10:05 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Weapons_Dev/Entities/Vehicles/Catapult/Catapult.as
> +				v.cooldown_time = Maths::Max(0,v.cooldown_time-this.get_f32("gyromat_acceleration"));
space after comma

2021-05-27 10:05 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Weapons_Dev/Entities/Vehicles/Catapult/Catapult.as
> +			if(this.exists("gyromat_acceleration"))
spacee

2021-05-27 10:05 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Weapons_Dev/Entities/Vehicles/Catapult/Catapult.as
> +		if(this.exists("gyromat_acceleration"))
.

2021-05-27 10:05 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Weapons_Dev/Entities/Vehicles/Catapult/Catapult.as
> +	if(this.exists("gyromat_acceleration"))
.

2021-05-27 10:05 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Weapons_Dev/Entities/Vehicles/Hoverbike/Hoverbike.as
> +			if(this.exists("gyromat_acceleration"))
.

2021-05-27 10:23 UTC, Wunarg commented
I fixed the spaces

2021-05-30 17:57 UTC, Vam-Jam approved these changes

2021-06-05 09:28 UTC, merged