Shifter
TFlippy/kag_territorycontrol pull request #174
Opened 2021-05-29 19:40 UTC by Wunarg

The shifter is a new building in the automation section, it does not have collision and is 1x1 big, when an entity collides with it that entity is moved in the direction of this rotatable building. After this the shifter starts a 120 tick cooldown. 
The force of the shifter is adjusted for mass and decreases to a minnimum the higher the velocity of the entity already is.
-Costs 20 wood, 10 stone and 2 copper coils (you usually need many of these)
Notes:
-the cooldown ensures that this does not protect against bombs greatly (one may be deflected or slowed to a a soft landing)
-the sprite changes slightly when recharge to indicate this
-the force is not strong enough to stop people from walking down a passage filled with them
-roughly 5 layers are needed to slow down a bombs from a low ish height
-particle accelerators are technicly possible (aka shifter circles) but extremely difficult due to corners and the cooldown
--Very fun
-Allows for many many fun things like elevators, people launchers, trampolines, railguns etc

2021-05-29 22:09 UTC, Gingerbeard5773 reviewed
Shifter is an interesting concept, however I believe that it is unfit for the mod because of its exploitable nature. Everything that the shifter does can be done by other parts of the mod and so I believe it is unneeded.

2021-05-29 22:09 UTC, Gingerbeard5773 commented on TFlippy_TerritoryControl_Characters_Dev/Entities/Characters/Builder/CommonBuilderBlocks.as
> +		{
Indent oopsie

2021-05-30 18:01 UTC, Vam-Jam requested changes

2021-05-30 18:01 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Structures_Dev/Entities/Structures/Factories/Shifter/Shifter.as
> +void onTick(CBlob@ this)
Optimization: Remove onTick and move the logic into onCollosion

Store last time used and if it's more > 120 ticks then push the blob


Put sprite animation into onTick(CSprite@)  so only clients will run that code

2021-05-30 18:01 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Structures_Dev/Entities/Structures/Factories/Shifter/Shifter.as
> +	if (this.get_u32("charge")>=120)
charge") space >= space 120

2021-06-02 09:46 UTC, Wunarg commented
Do not add this one yet on my end it has crashed sometimes randomly for a completely unknown reason and while it might be related to my computer specificly i would like to figure it out before unleashing it on the server.

2021-06-05 21:48 UTC, xcs011 commented
shifter added when

2021-06-05 21:48 UTC, xcs011 commented
just ignore dragon and ginger they just hate anything "fun" because it wont let them tryhard and kill neutrals harder

2021-06-06 02:09 UTC, xcs011 commented
vamist you can oh whats this ban button do all you want, but you know for a fact something not having a use aside from being fun is a retarded reason not to add it

2021-06-06 02:10 UTC, xcs011 commented
Heres a novel idea, what if we added fun and engaging things to tc, instead of just shitting about the faction neutral balance for all eternity

2021-06-22 09:40 UTC, merged