Minicopter
TFlippy/kag_territorycontrol pull request #224
Opened 2021-07-04 06:34 UTC by xcs011

Added a smaller, much weaker helicopter for fun
Seats two people, one gunner, with a bobby gun mounted on the front, and a driver

Takes fuel or oil

2021-07-04 06:48 UTC, xcs011 commented
nugget did the sprite 

nugget stop complaining see I did it

2021-07-04 06:49 UTC, Jim-Smiff commented
tested with no bugs 100% fine and fun

2021-07-04 07:25 UTC, xcs011 commented
we even tested this, are you proud of me vamist?

2021-07-04 08:14 UTC, xcs011 commented
Either I'm dumb or github is, one of us deleted the Readme by accident, I'll fix it tomorrow

2021-07-04 08:29 UTC, xcs011 commented
I highly doubt you will deal with this tomorrow vamist, but don't, upon further reflection the PR needs a little more tweaking:

TODO:
github vored the readme fix that shit
make heli grapplable because its funny

possibly add a wooden crate attachment slot _up for debate_

2021-07-04 09:20 UTC, Vam-Jam requested changes
Re-check what you've commited, you've removed zip, meteor shittery and build_release

2021-07-04 13:18 UTC, xcs011 commented
Yeah meteor is still out so I can test, will be fixed.
I honestly don't know when build_release and all that got deleted, Readme vanished at one point too

2021-07-04 13:56 UTC, Vam-Jam commented
> Yeah meteor is still out so I can test, will be fixed.
> I honestly don't know when build_release and all that got deleted, Readme vanished at one point too

You dont have to commit all edited files, git allows you to select what files you'd like to commit, the rest got deleted because KAG will remove files it cant send to clients (e.g. anything aside from .as, .ogg and so on)

2021-07-05 02:18 UTC, xcs011 commented
dont worry about all the readme shit
god I fucking hate resolving issues

2021-07-05 02:19 UTC, xcs011 commented
@Vam-Jam just merge it if its good, ill do an attachment update later for the crate and gramophone

2021-07-07 04:15 UTC, xcs011 commented
@Vam-Jam test already nerd, also I finished letting noisemakers and gramophones attach and detach

2021-07-07 04:17 UTC, xcs011 reviewed
They done

2021-07-07 05:18 UTC, xcs011 commented
I found the funny request review button also wrecks added

2021-07-07 11:40 UTC, Vam-Jam requested changes

2021-07-07 11:40 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Weapons_Dev/Entities/Vehicles/Helichopper/Helichopper.as
> +	//this.Tag("helicopter");    					remind laika later when someone finally sees this
.

2021-07-07 11:40 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Patreon_Dev/Items/Noisemaker/Noisemaker.cfg
> +										  CARGO; 0; -10; 1; 0; 0;
indents

2021-07-07 11:40 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Weapons_Dev/Entities/Vehicles/Helichopper/Helichopper.cfg
> +													CARGO; 0; 14;  0; 0; 0;
indents

2021-07-07 11:40 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Weapons_Dev/Entities/Vehicles/Wreck/MinicopterWreck.cfg
> +											 Wreck.as;
indents

2021-07-08 17:57 UTC, merged