Darkie changes
TFlippy/kag_territorycontrol pull request #243
Opened 2021-07-19 19:53 UTC by TC-DarkSlayer

Since "4x bullet" bug was supposedly fixed, armor durability was scaled back down again, but its durability is still better than previous update.
Reduced knockback from shotguns by 30% as shotguns shoots a lot more bullets than other guns, causing people to fly in the air due to the sheer knockback.

2021-07-19 20:15 UTC, xcs011 commented
literally when you crackhead
unless it was fixed in actually the last 8 hours it didnt happen

2021-07-19 20:16 UTC, xcs011 commented
also why do you have two separate githubs to make the pr with one and commit with the other wth

2021-07-19 23:44 UTC, TC-DarkSlayer commented
> also why do you have two separate githubs to make the pr with one and commit with the other wth

Forgot account pass then remembered
Unless you're talking about why I have 3 branches

2021-07-20 00:06 UTC, xcs011 commented
Also @TC-DarkSlayer the knockback change is no longer needed, it was due to the 4x damage glitch as well

Shotguns also shot 4x the number of pellets, and had 4x the knockback

2021-07-20 12:21 UTC, Vam-Jam requested changes

2021-07-20 12:21 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Misc_Dev/Entities/Equipment/MilitaryHelmet/militaryhelmet_effect.as
> +		milhelmet.SetFrameIndex(Maths::Floor(this.get_f32("militaryhelmet_health") / 7.51f));
indent

2021-07-20 15:22 UTC, Vam-Jam commented
Holding this back an update (will include in a hotfix). Waiting to see if bullet damage is finally fixed

2021-07-21 14:10 UTC, Vam-Jam requested changes

2021-07-21 14:10 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Core_Dev/Entities/FleshHit.as
> +			f32 armorMaxHealth=10.0f;
armorMaxHealth = 10.0f, space for readability

2021-07-21 14:10 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Core_Dev/Entities/FleshHit.as
> +			f32 armorMaxHealth=10.0f;
same here

2021-07-21 14:10 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Core_Dev/Entities/FleshHit.as
> +			f32 ratio=0.0f;
and here

2021-07-21 14:10 UTC, Vam-Jam commented
also fix merge conflicts if you can

2021-07-21 16:44 UTC, TC-DarkSlayer commented
This PR was based on a PR that was reverted
Requires this revert to be reverted 
![image](https://user-images.githubusercontent.com/68712994/126526850-5646276d-418e-4d5a-98c9-9c138bf19bf0.png)

2021-07-28 08:15 UTC, TC-DarkSlayer reviewed
- Building Druglab gives 25% chance to give you chemistry blueprint
(may tweak percent chances later on, we'll see for now how this gacha mechanic goes)

2021-07-28 23:22 UTC, TC-DarkSlayer commented
Current Summary:
- New Armor : Scubagear, minershelmet, pumpkin, combatboots (now protects minor damage)
- Ballistic Armor now has more durability
   - Helm: 20 to 25 health
   - BulProof Vest: 25 to 30 health
- Shotgun 30% less knockback
- Repairable Armor and Bushyhelmet(camo) upgrade
- Tinkertable now sorted
- Lighter costs a lantern instead of oil
- Grinder gives a little bit more wood
- Placing backwalls gives coins
- Food is now stacked into one blob, reducing lag
- Juggernaut can now use V to eat 
- PlayerChickens can now throw grenades
- Fixed teamstorage bugs
- Kudzu no longer has damage reduction from bullets/bombs
- Kudzu can now be damaged by radiation
- Making Druglabs has chance of dropping blueprint: Chemistry
- Blueprints will no longer be consumed

2021-07-29 07:55 UTC, Wunarg commented
Really not a fan of the kudzu damage resistances changes, since defeating kudzu with bombs and bullets removes one of the intersting aspects of kudzu of needing to use other weaponary, instead of the weaponary used everywhere else

2021-07-29 08:19 UTC, TC-DarkSlayer commented
> Really not a fan of the kudzu damage resistances changes, since defeating kudzu with bombs and bullets removes one of the intersting aspects of kudzu of needing to use other weaponary, instead of the weaponary used everywhere else

Was pain in a neck to destroy kudzu cores, took me around 8 dynamite per kudzucore(kudzu tiles kept regening) vs mason's 15 kudzu cores

2021-07-29 08:26 UTC, Wunarg commented
> 
> 
> > Really not a fan of the kudzu damage resistances changes, since defeating kudzu with bombs and bullets removes one of the intersting aspects of kudzu of needing to use other weaponary, instead of the weaponary used everywhere else
> 
> Was pain in a neck to destroy kudzu cores, took me around 8 dynamite per kudzucore(kudzu tiles kept regening) vs mason's 15 kudzu cores
thats what i mean though, your not supposed to use explosives against kudzu

2021-08-02 02:11 UTC, xcs011 commented
I don't think shotgun needs a further knockback nerf, as that was majorly fixed when the 4x bullets bug was.
It would also almost make more sense to just make the chemlab have a chance to drop the blueprint when created, like you got experience from building it, and made the blueprint

2021-08-02 02:12 UTC, xcs011 commented
Reducing dirt bullet resistance is eh too, rather I think it should be like neutrals with concrete, where they can damage it, but never fully break it

2021-08-02 02:13 UTC, McSaucyNugget commented
neuts can completely break concrete, your thinking of reinforced steel concrete. Also autochemlab should drop its blueprint everytime its destroyed, along with the missile assembler and the sun tower

2021-08-02 02:14 UTC, xcs011 commented
Oh, I literally meant that the normal chem lab should have a chance to drop it on construction, albeit a small chance, and yeah I was thinking about reinforced

2021-08-02 02:15 UTC, xcs011 commented
That or ill finally add a sandbag block to absorb bullets

2021-08-02 05:07 UTC, xcs011 commented
> 
> 
> Really not a fan of the kudzu damage resistances changes, since defeating kudzu with bombs and bullets removes one of the intersting aspects of kudzu of needing to use other weaponary, instead of the weaponary used everywhere else

I mean yeah but why wouldnt a plant be just as vulnerable to explosives

2021-08-02 12:52 UTC, Vam-Jam requested changes

2021-08-02 12:52 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Misc_Dev/Entities/Misc/Kudzu/KudzuCore.as
> +					case 389592510:		matReq = 1;		break;	// badger
indent

2021-08-02 12:52 UTC, Vam-Jam commented on TFlippy_TerritoryControl_Misc_Dev/Entities/Misc/Kudzu/KudzuCore.as
> +		}
space

2021-08-02 12:52 UTC, Vam-Jam commented
This PR has gotten too big, I'll sit down and review it when I get the time.

2021-08-11 02:29 UTC, TC-DarkSlayer commented
Splitting this PR

2021-08-11 02:29 UTC, closed without merging